### ISSUE TITLE
Error while booting include file

### ISSUE THREAD

**Issue by FlogFr** [novafloss/pdoc.boot#11]
Impossible to boot a container since I updated the requirements:

```
TASK [novafloss.boot : include] ************************************************
fatal: [localhost]: FAILED! => {"failed": true, "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/home/arkadefr/Projects/django-novaauth/ansible/roles/novafloss.boot/tasks/lxd.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Start lxd container\n  ^ here\n\n\nThe error appears to have been in '/home/arkadefr/Projects/django-novaauth/ansible/roles/novafloss.boot/tasks/lxd.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Start lxd container\n  ^ here\n"}
```

**Comment by indispeq** [comment]
I am getting the same issue on this version of novafloss.boot, rendering my tests unbootable. I was not able to see the problem, unless I disabled LXD. @jpic any ideas?

Is this because our machines are missing the LXD patch you created?

**Comment by jpic** [comment]
LXD works and is tested but we can't test LXC on travis, so ​the
combination of having LXC and not LXD was not tested, sorry this was right
before my hollidays. My recommendation would have been for you to revert
the commits during my leave - that's how continuous integration works @
google for example. Thanks for the reminder though, I'm fixing this !
